# Generated by Django 4.0.3 on 2022-03-10 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicrater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('idd', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('song', models.CharField(max_length=100)),
                ('rating', models.IntegerField(max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicrater.user')),
            ],
        ),
    ]
