# Generated by Django 4.0.3 on 2022-03-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicrater', '0002_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='idd',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
