# Generated by Django 4.0.3 on 2022-04-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicrater', '0007_album_artist_delete_question_rating_billboardranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('song', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='rating',
            name='billboardranking',
            field=models.IntegerField(default=-1),
        ),
    ]
