# Generated by Django 4.0.3 on 2022-04-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicrater', '0008_userrating_alter_rating_billboardranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
