# Generated by Django 4.0.3 on 2022-04-14 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicrater', '0009_song_delete_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicrater.song'),
        ),
    ]
