# Generated by Django 4.0.3 on 2022-04-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicrater', '0010_alter_userrating_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='song',
            field=models.CharField(max_length=100),
        ),
    ]
